// Generated seed content module. Edit directly; kept split by campaign data typology.
import { api } from "./client.js";
import { CMP } from "./config.js";
import * as ids from "./ids.js";

// ---------------------------------------------------------------------------
// Pre-made characters
// ---------------------------------------------------------------------------

export async function seedPreMadeCharacters() {
  const PREMADE = [
    {
      entityId: ids.ENT_PC_ELOWYN,
      entityType: "player_character",
      title: "Elowyn Darkwater",
      summary: "Elfa pícara. Especialista en infiltración y engaño. Busca algo que le fue arrebatado.",
      status: "active",
      importance: "normal",
      metadata: {
        isPremade: true,
        className: "Pícaro",
        level: 1,
        species: "Elfo",
        background: "Forajida",
        armorClass: 14,
        hitPointsCurrent: 8,
        hitPointsMax: 8,
        hitPointsTemp: 0,
        hitDice: "1d8",
        speed: 30,
        initiative: 3,
        passivePerception: 14,
        passiveInsight: 12,
        passiveInvestigation: 13,
        strength: 8,
        dexterity: 17,
        constitution: 12,
        intelligence: 13,
        wisdom: 14,
        charisma: 10,
        savingThrows: ["dex", "int"],
        skills: ["acrobatics", "stealth", "perception", "sleight_of_hand"],
        languages: ["comun", "elfico"],
        feats: ["Alerta"],
        xp: 0,
        note: "Personaje pre-hecho. Sin jugador asignado.",
      },
    },
    {
      entityId: ids.ENT_PC_CAMUS,
      entityType: "player_character",
      title: "Hermano Camus",
      summary: "Clérigo humano del Templo de la Verdad. Busca redención por un pasado que prefiere no recordar.",
      status: "active",
      importance: "normal",
      metadata: {
        isPremade: true,
        className: "Clérigo",
        level: 1,
        species: "Humano",
        background: "Acólito",
        armorClass: 16,
        hitPointsCurrent: 9,
        hitPointsMax: 9,
        hitPointsTemp: 0,
        hitDice: "1d8",
        speed: 30,
        initiative: 0,
        passivePerception: 15,
        passiveInsight: 15,
        passiveInvestigation: 10,
        strength: 14,
        dexterity: 10,
        constitution: 14,
        intelligence: 10,
        wisdom: 16,
        charisma: 12,
        savingThrows: ["wis", "cha"],
        skills: ["insight", "medicine", "religion", "history"],
        languages: ["comun", "celestial"],
        feats: ["Iniciacion_Magica"],
        xp: 0,
        note: "Personaje pre-hecho. Sin jugador asignado.",
      },
    },
    {
      entityId: ids.ENT_PC_RAGNA,
      entityType: "player_character",
      title: "Ragna Ironsong",
      summary: "Guerrera enana. Sirvió en la guardia de Valdris durante años. Conoce la ciudad mejor que nadie.",
      status: "active",
      importance: "normal",
      metadata: {
        isPremade: true,
        className: "Guerrero",
        level: 1,
        species: "Enano",
        background: "Soldado",
        armorClass: 18,
        hitPointsCurrent: 12,
        hitPointsMax: 12,
        hitPointsTemp: 0,
        hitDice: "1d10",
        speed: 30,
        initiative: 1,
        passivePerception: 13,
        passiveInsight: 11,
        passiveInvestigation: 9,
        strength: 16,
        dexterity: 12,
        constitution: 15,
        intelligence: 8,
        wisdom: 12,
        charisma: 10,
        savingThrows: ["str", "con"],
        skills: ["athletics", "intimidation", "perception", "survival"],
        languages: ["comun", "enano"],
        feats: ["Duro"],
        xp: 0,
        note: "Personaje pre-hecho. Sin jugador asignado.",
      },
    },
    {
      entityId: ids.ENT_PC_SILAS,
      entityType: "player_character",
      title: "Silas el Errante",
      summary: "Bardo mediano. Coleccionista de historias y secretos. Nadie sabe exactamente de dónde viene.",
      status: "active",
      importance: "normal",
      metadata: {
        isPremade: true,
        className: "Bardo",
        level: 1,
        species: "Mediano",
        background: "Embaucador",
        armorClass: 13,
        hitPointsCurrent: 7,
        hitPointsMax: 7,
        hitPointsTemp: 0,
        hitDice: "1d8",
        speed: 30,
        initiative: 2,
        passivePerception: 12,
        passiveInsight: 10,
        passiveInvestigation: 12,
        strength: 8,
        dexterity: 14,
        constitution: 13,
        intelligence: 12,
        wisdom: 10,
        charisma: 16,
        savingThrows: ["dex", "cha"],
        skills: ["deception", "performance", "persuasion", "insight"],
        languages: ["comun", "mediano"],
        feats: ["Afortunado"],
        xp: 0,
        note: "Personaje pre-hecho. Sin jugador asignado.",
      },
    },
  ];

  for (const pc of PREMADE) {
    await api("POST", `/api/campaigns/${CMP}/entities`, { ...pc, actorId: "usr_dm" });
  }
  console.log(`✓ ${PREMADE.length} pre-made characters created (sin jugadores asignados)`);
}
