import { apiFetch } from "./apiClient.js";
const jsonInit = (method: string, body?: unknown): RequestInit => ({ method, headers: { "Content-Type": "application/json" }, ...(body === undefined ? {} : { body: JSON.stringify(body) }) });
export const getPlayerCampaign = (campaignId: string) => apiFetch(`/api/campaigns/${campaignId}/player-portal/state`);
export const getPlayerHome = getPlayerCampaign;
export const getPlayerMemory = getPlayerCampaign;
export const getPlayerConstellation = getPlayerCampaign;
export const getPlayerCharacter = getPlayerCampaign;
export const getPlayerObjectives = getPlayerCampaign;
export const getPlayerRecap = getPlayerCampaign;
export const getPlayerNotes = getPlayerCampaign;
export const getPlayerProposals = getPlayerCampaign;
export const getPlayerPortalState = getPlayerCampaign;
export const updatePlayerPortalStatus = (campaignId: string, payload: unknown) => apiFetch(`/api/campaigns/${campaignId}/player-portal/status`, { init: jsonInit("PUT", payload) });
export const createPlayerPortalResource = (campaignId: string, payload: unknown) => apiFetch(`/api/campaigns/${campaignId}/player-portal/resources`, { init: jsonInit("POST", payload) });
export const updatePlayerPortalResource = (campaignId: string, resourceId: string, payload: unknown) => apiFetch(`/api/campaigns/${campaignId}/player-portal/resources/${resourceId}`, { init: jsonInit("PUT", payload) });
export const createPlayerPortalNote = (campaignId: string, payload: unknown) => apiFetch(`/api/campaigns/${campaignId}/player-portal/notes`, { init: jsonInit("POST", payload) });
export const updatePlayerPortalNote = (campaignId: string, noteId: string, payload: unknown) => apiFetch(`/api/campaigns/${campaignId}/player-portal/notes/${noteId}`, { init: jsonInit("PUT", payload) });
export const createPlayerPortalObjective = (campaignId: string, payload: unknown) => apiFetch(`/api/campaigns/${campaignId}/player-portal/objectives`, { init: jsonInit("POST", payload) });
export const updatePlayerPortalObjective = (campaignId: string, objectiveId: string, payload: unknown) => apiFetch(`/api/campaigns/${campaignId}/player-portal/objectives/${objectiveId}`, { init: jsonInit("PUT", payload) });
export const createPlayerPortalProposal = (campaignId: string, payload: unknown) => apiFetch(`/api/campaigns/${campaignId}/player-portal/proposals`, { init: jsonInit("POST", payload) });
export const getPlayerPortalDmSummary = (campaignId: string) => apiFetch(`/api/campaigns/${campaignId}/player-portal/dm-character-summary`);
export const resolvePlayerPortalProposal = (campaignId: string, proposalId: string, payload: unknown) => apiFetch(`/api/campaigns/${campaignId}/player-portal/proposals/${proposalId}/resolve`, { init: jsonInit("PUT", payload) });
export const linkPlayerCharacter = (campaignId: string, payload: unknown) => apiFetch(`/api/campaigns/${campaignId}/player-portal/links`, { init: jsonInit("POST", payload) });
export const unlinkPlayerCharacter = (campaignId: string, playerId: string) => apiFetch(`/api/campaigns/${campaignId}/player-portal/links/${playerId}`, { init: { method: "DELETE" } });
