import { z } from "zod";
import { eventIdSchema, campaignIdSchema } from "@shared/schemas.js";
import { campaignSchema, campaignSettingsSchema } from "../campaign/types.js";
import { playerProfileSchema } from "../campaign/player.js";
import { entitySchema, baseEntitySchema } from "../entity/types.js";
import { relationSchema, baseRelationSchema } from "../relation/types.js";
import { factSchema } from "../fact/types.js";
import { sessionSchema, sessionEventSchema, sessionStatusSchema, sessionPrepSchema } from "../session/types.js";
import { visibilityRuleSchema } from "@shared/schemas.js";
import { revelationAnchorSchema } from "../entity/revelationAnchors.js";

export const canvasViewportSchema = z.object({
  x: z.number(),
  y: z.number(),
  zoom: z.number(),
});

export const canvasNodeSchema = z.object({
  id: z.string(),
  campaignId: z.string(),
  canvasId: z.string(),
  kind: z.enum(["entity", "note", "group", "image", "fact"]),
  entityId: z.string().optional(),
  factId: z.string().optional(),
  text: z.string().optional(),
  title: z.string().optional(),
  color: z.enum(["yellow", "blue", "green", "pink", "purple"]).optional(),
  x: z.number(),
  y: z.number(),
  width: z.number().optional(),
  height: z.number().optional(),
  collapsed: z.boolean().optional(),
  zIndex: z.number().optional(),
  status: z.enum(["draft", "ready", "revealed", "resolved"]).optional(),
  visibility: z.enum(["dm", "public"]).optional(),
  groupId: z.string().optional(),
  parentId: z.string().optional(),
  metadata: z.record(z.string(), z.unknown()).optional(),
  createdAt: z.string(),
  updatedAt: z.string(),
});

export const canvasEdgeSchema = z.object({
  id: z.string(),
  campaignId: z.string(),
  canvasId: z.string(),
  sourceNodeId: z.string(),
  targetNodeId: z.string(),
  relationshipId: z.string().optional(),
  label: z.string().optional(),
  status: z.enum(["draft", "domain"]),
  visibility: z.enum(["dm", "public"]).optional(),
  style: z.enum(["solid", "dashed", "secret", "weak", "strong"]).optional(),
  metadata: z.record(z.string(), z.unknown()).optional(),
  createdAt: z.string(),
  updatedAt: z.string(),
});

const canvasNodeUpdatesSchema = z.object({
  text: z.string().optional(),
  title: z.string().optional(),
  color: z.enum(["yellow", "blue", "green", "pink", "purple"]).optional(),
  x: z.number().finite().optional(),
  y: z.number().finite().optional(),
  width: z.number().finite().nonnegative().optional(),
  height: z.number().finite().nonnegative().optional(),
  collapsed: z.boolean().optional(),
  zIndex: z.number().finite().optional(),
  status: z.enum(["draft", "ready", "revealed", "resolved"]).optional(),
  visibility: z.enum(["dm", "public"]).optional(),
  groupId: z.string().nullable().optional(),
  parentId: z.string().nullable().optional(),
  metadata: z.record(z.string(), z.unknown()).optional(),
}).strict();

const canvasEdgeUpdatesSchema = z.object({
  label: z.string().optional(),
  status: z.enum(["draft", "domain"]).optional(),
  visibility: z.enum(["dm", "public"]).optional(),
  style: z.enum(["solid", "dashed", "secret", "weak", "strong"]).optional(),
  metadata: z.record(z.string(), z.unknown()).optional(),
}).strict();

export const canvasSchema = z.object({
  id: z.string(),
  campaignId: z.string(),
  title: z.string(),
  kind: z.enum(["world", "session", "mystery", "location", "characters", "custom"]),
  description: z.string().optional(),
  nodes: z.array(canvasNodeSchema),
  edges: z.array(canvasEdgeSchema),
  viewport: canvasViewportSchema,
  archived: z.boolean(),
  createdAt: z.string(),
  updatedAt: z.string(),
});

export const domainEventTypeSchema = z.enum([
  "VaultCreated",
  "CampaignCreated",
  "CampaignUpdated",
  "PlayerProfileCreated",
  "PlayerProfileUpdated",
  "PlayerProfileArchived",
  "PlayerInvitationCreated",
  "PlayerInvitationConsumed",
  "PlayerInvitationRevoked",
  "EntityCreated",
  "EntityUpdated",
  "EntityArchived",
  "RelationCreated",
  "RelationUpdated",
  "RelationArchived",
  "FactCreated",
  "FactUpdated",
  "FactArchived",
  "VisibilityChanged",
  "ClueRevealed",
  "SessionCreated",
  "SessionStarted",
  "SessionPrepUpdated",
  "SessionClosed",
  "SessionCancelled",
  "SessionArchived",
  "SessionEventRecorded",
  "AttachmentAdded",
  "AttachmentRemoved",
  "TagCreated",
  "TagUpdated",
  "ImportCompleted",
  "ExportCompleted",
  "SnapshotCreated",
  "SettingsUpdated",
  "CanvasCreated",
  "CanvasUpdated",
  "CanvasArchived",
  "CanvasNodePlaced",
  "CanvasNodeUpdated",
  "CanvasNodesLayoutUpdated",
  "CanvasNodeRemoved",
  "CanvasEdgeAdded",
  "CanvasEdgeUpdated",
  "CanvasEdgeRemoved",
  "CanvasNoteConvertedToEntity",
  "PlayerTokenIssued",
  "PlayerTokenRevoked",
  "PlayerCharacterLinked",
  "PlayerCharacterUnlinked",
  "PlayerCharacterLiveStateUpdated",
  "PlayerResourceUpserted",
  "PlayerResourceRemoved",
  "PlayerPortalNoteCreated",
  "PlayerPortalNoteUpdated",
  "PlayerPortalNoteArchived",
  "PlayerPortalObjectiveCreated",
  "PlayerPortalObjectiveUpdated",
  "PlayerPortalObjectiveArchived",
  "PlayerCharacterProposalCreated",
  "PlayerCharacterProposalResolved",
]);

export type DomainEventType = z.infer<typeof domainEventTypeSchema>;

export const storedEventSchema = z.object({
  sequence: z.number().int().nonnegative(),
  eventId: eventIdSchema,
  campaignId: campaignIdSchema.optional(),
  type: domainEventTypeSchema,
  occurredAt: z.string(),
  actorId: z.string(),
  payload: z.unknown(),
  previousHash: z.string().optional(),
  hash: z.string().optional(),
  schemaVersion: z.number().int().default(1),
  commandId: z.string().optional(),
  commandHash: z.string().optional(),
});

export type StoredEvent<TPayload = any> = z.infer<typeof storedEventSchema> & {
  payload: TPayload;
};

// Event payload schemas helper
export const eventPayloadSchemas = {
  VaultCreated: z.object({ name: z.string() }),
  CampaignCreated: campaignSchema,
  CampaignUpdated: campaignSchema.partial().extend({ id: campaignIdSchema }),
  PlayerProfileCreated: playerProfileSchema,
  PlayerProfileUpdated: playerProfileSchema.partial().extend({ id: z.string() }),
  PlayerProfileArchived: z.object({ id: z.string().optional(), playerId: z.string().optional() }),
  EntityCreated: entitySchema,
  EntityUpdated: baseEntitySchema.partial().extend({ id: z.string().optional(), entityId: z.string().optional() }),
  EntityArchived: z.object({ id: z.string().optional(), entityId: z.string().optional() }),
  RelationCreated: relationSchema,
  RelationUpdated: baseRelationSchema.partial().extend({ id: z.string().optional(), relationId: z.string().optional() }),
  RelationArchived: z.object({ id: z.string() }),
  FactCreated: factSchema,
  FactUpdated: factSchema.partial().extend({ id: z.string() }),
  FactArchived: z.object({ id: z.string() }),
  VisibilityChanged: z.object({
    targetId: z.string(),
    targetType: z.enum(["entity", "relation", "fact"]),
    visibility: visibilityRuleSchema,
    sessionId: z.string().optional(),
    note: z.string().optional(),
  }),
  ClueRevealed: z.object({
    clueEntityId: z.string(),
    sessionId: z.string(),
    visibility: visibilityRuleSchema,
    note: z.string().optional(),
    revelationAnchors: z.array(revelationAnchorSchema).optional(),
  }),
  SessionCreated: sessionSchema,
  SessionPrepUpdated: sessionSchema,
  SessionStarted: z.object({
    id: z.string(),
    startedAt: z.string(),
    campaignId: campaignIdSchema.optional(),
    number: z.number().int().min(1).optional(),
    title: z.string().min(1).optional(),
    status: sessionStatusSchema.optional(),
    prep: sessionPrepSchema.optional(),
  }),
  SessionClosed: z.object({
    id: z.string(),
    endedAt: z.string(),
    summary: z.string().optional(),
    playerSummary: z.string().optional(),
    campaignId: campaignIdSchema.optional(),
    number: z.number().int().min(1).optional(),
    title: z.string().min(1).optional(),
    status: sessionStatusSchema.optional(),
    prep: sessionPrepSchema.optional(),
  }),
  SessionCancelled: sessionSchema,
  SessionArchived: sessionSchema,
  SessionEventRecorded: sessionEventSchema,
  AttachmentAdded: z.object({
    id: z.string(),
    filename: z.string(),
    mimeType: z.string(),
    sizeBytes: z.number(),
  }),
  AttachmentRemoved: z.object({ id: z.string() }),
  TagCreated: z.object({ id: z.string(), name: z.string(), color: z.string().optional() }),
  TagUpdated: z.object({ id: z.string(), name: z.string().optional(), color: z.string().optional() }),
  ImportCompleted: z.object({ importId: z.string(), format: z.string(), count: z.number() }),
  ExportCompleted: z.object({ exportId: z.string(), format: z.string() }),
  SnapshotCreated: z.object({ sequence: z.number().int() }),
  SettingsUpdated: campaignSettingsSchema,
  CanvasCreated: canvasSchema,
  CanvasUpdated: z.object({
    canvasId: z.string(),
    title: z.string().optional(),
    viewport: canvasViewportSchema.optional(),
    description: z.string().optional(),
  }),
  CanvasArchived: z.object({
    canvasId: z.string(),
  }),
  CanvasNodePlaced: z.object({
    canvasId: z.string(),
    node: canvasNodeSchema,
  }),
  CanvasNodeUpdated: z.object({
    canvasId: z.string(),
    nodeId: z.string(),
    updates: canvasNodeUpdatesSchema,
  }),
  CanvasNodesLayoutUpdated: z.object({
    canvasId: z.string(),
    nodeUpdates: z.array(z.object({
      nodeId: z.string(),
      x: z.number().finite(),
      y: z.number().finite(),
      width: z.number().finite().nonnegative().optional(),
      height: z.number().finite().nonnegative().optional(),
      parentId: z.string().nullable().optional(),
      groupId: z.string().nullable().optional(),
    })),
  }),
  CanvasNodeRemoved: z.object({
    canvasId: z.string(),
    nodeId: z.string(),
  }),
  CanvasEdgeAdded: z.object({
    canvasId: z.string(),
    edge: canvasEdgeSchema,
  }),
  CanvasEdgeUpdated: z.object({
    canvasId: z.string(),
    edgeId: z.string(),
    updates: canvasEdgeUpdatesSchema,
  }),
  CanvasEdgeRemoved: z.object({
    canvasId: z.string(),
    edgeId: z.string(),
  }),
  CanvasNoteConvertedToEntity: z.union([
    z.object({
      canvasId: z.string(),
      nodeId: z.string(),
      entityId: z.string(),
    }),
    z.object({
      canvasId: z.string(),
      nodeId: z.string(),
      entity: entitySchema,
    }),
  ]),
  PlayerTokenIssued: z.object({
    tokenId: z.string().min(1),
    tokenHash: z.string().min(1),
    campaignId: z.string().min(1),
    playerId: z.string().min(1),
    label: z.string().optional(),
    createdAt: z.string().min(1),
  }),
  PlayerTokenRevoked: z.object({
    tokenId: z.string().min(1),
    campaignId: z.string().min(1),
    revokedAt: z.string().min(1),
  }),
  PlayerCharacterLinked: z.object({
    campaignId: z.string().min(1),
    playerId: z.string().min(1),
    characterEntityId: z.string().min(1),
    ownership: z.enum(["campaign_premade", "player_owned"]),
    syncMode: z.enum(["live_player_editable", "dm_review_required"]),
    createdAt: z.string().min(1),
    updatedAt: z.string().min(1),
  }),
  PlayerCharacterUnlinked: z.object({
    campaignId: z.string().min(1),
    playerId: z.string().min(1),
    characterEntityId: z.string().min(1),
    unlinkedAt: z.string().min(1),
  }),
  PlayerCharacterLiveStateUpdated: z.object({
    campaignId: z.string().min(1),
    playerId: z.string().min(1),
    characterEntityId: z.string().min(1),
    status: z.object({
      hitPointsCurrent: z.number().int().optional(),
      hitPointsMax: z.number().int().optional(),
      armorClass: z.number().int().optional(),
      inspiration: z.boolean().optional(),
      conditions: z.array(z.string()).optional(),
    }),
    updatedBy: z.enum(["player", "dm"]),
    updatedAt: z.string().min(1),
  }),
  PlayerResourceUpserted: z.object({
    campaignId: z.string().min(1),
    playerId: z.string().min(1),
    characterEntityId: z.string().min(1),
    resource: z.object({
      resourceId: z.string().min(1),
      label: z.string().min(1),
      current: z.number().int(),
      max: z.number().int(),
      recovery: z.enum(["short_rest", "long_rest", "manual"]).optional(),
    }),
    updatedBy: z.enum(["player", "dm"]).optional(),
    updatedAt: z.string().min(1),
  }),
  PlayerResourceRemoved: z.object({
    campaignId: z.string().min(1),
    playerId: z.string().min(1),
    characterEntityId: z.string().min(1),
    resourceId: z.string().min(1),
    removedAt: z.string().min(1),
  }),
  PlayerPortalNoteCreated: z.object({
    noteId: z.string().min(1),
    campaignId: z.string().min(1),
    playerId: z.string().min(1),
    title: z.string().min(1),
    content: z.string(),
    visibility: z.enum(["private", "dm_visible"]),
    linkedEntityIds: z.array(z.string()),
    createdAt: z.string().min(1),
    updatedAt: z.string().min(1),
  }),
  PlayerPortalNoteUpdated: z.object({
    noteId: z.string().min(1),
    campaignId: z.string().min(1),
    playerId: z.string().min(1),
    title: z.string().optional(),
    content: z.string().optional(),
    visibility: z.enum(["private", "dm_visible"]).optional(),
    linkedEntityIds: z.array(z.string()).optional(),
    archived: z.boolean().optional(),
    updatedAt: z.string().min(1),
  }),
  PlayerPortalNoteArchived: z.object({
    noteId: z.string().min(1),
    campaignId: z.string().min(1),
    playerId: z.string().min(1),
    archivedAt: z.string().min(1),
  }),
  PlayerPortalObjectiveCreated: z.object({
    objectiveId: z.string().min(1),
    campaignId: z.string().min(1),
    playerId: z.string().min(1),
    title: z.string().min(1),
    description: z.string().optional(),
    kind: z.enum(["personal", "session", "question_for_dm"]),
    status: z.enum(["open", "done", "archived"]),
    visibility: z.enum(["private", "dm_visible"]),
    linkedEntityIds: z.array(z.string()),
    createdAt: z.string().min(1),
    updatedAt: z.string().min(1),
  }),
  PlayerPortalObjectiveUpdated: z.object({
    objectiveId: z.string().min(1),
    campaignId: z.string().min(1),
    playerId: z.string().min(1),
    title: z.string().optional(),
    description: z.string().optional(),
    kind: z.enum(["personal", "session", "question_for_dm"]).optional(),
    status: z.enum(["open", "done", "archived"]).optional(),
    visibility: z.enum(["private", "dm_visible"]).optional(),
    linkedEntityIds: z.array(z.string()).optional(),
    updatedAt: z.string().min(1),
  }),
  PlayerPortalObjectiveArchived: z.object({
    objectiveId: z.string().min(1),
    campaignId: z.string().min(1),
    playerId: z.string().min(1),
    archivedAt: z.string().min(1),
  }),
  PlayerCharacterProposalCreated: z.object({
    proposalId: z.string().min(1),
    campaignId: z.string().min(1),
    playerId: z.string().min(1),
    targetCharacterEntityId: z.string().optional(),
    kind: z.enum(["create_character", "update_character_core", "link_request"]),
    status: z.enum(["pending", "approved", "rejected"]),
    proposedChanges: z.record(z.string(), z.unknown()),
    createdAt: z.string().min(1),
  }),
  PlayerCharacterProposalResolved: z.object({
    proposalId: z.string().min(1),
    campaignId: z.string().min(1),
    playerId: z.string().min(1),
    status: z.enum(["approved", "rejected"]),
    dmResolutionNote: z.string().optional(),
    resolvedAt: z.string().min(1),
  }),
};
export type EventPayloads = {
  [K in keyof typeof eventPayloadSchemas]: z.infer<(typeof eventPayloadSchemas)[K]>;
};
