import { api } from "./client.js";
import { CMP } from "./config.js";
import * as ids from "./ids.js";

export async function seedPreMadeCharacters() {
  const PREMADE = [
    {
      entityId: ids.ENT_PC_ARIC,
      entityType: "player_character",
      title: "Aric Veldan",
      summary: "Guerrero humano, escolta de caravanas. Quiere demostrar que vale más que una espada contratada.",
      status: "active",
      importance: "normal",
      visibility: { kind: "party" },
      metadata: {
        isPremade: true,
        className: "Guerrero",
        level: 1,
        species: "Humano",
        background: "Soldado",
        armorClass: 17,
        hitPointsCurrent: 12,
        hitPointsMax: 12,
        hitDice: "1d10",
        speed: 30,
        initiative: 1,
        passivePerception: 13,
        passiveInsight: 11,
        passiveInvestigation: 10,
        strength: 16,
        dexterity: 12,
        constitution: 15,
        intelligence: 10,
        wisdom: 13,
        charisma: 10,
        skills: ["athletics", "perception", "intimidation"],
        note: "Personaje pre-hecho disponible para elegir desde el portal de jugador.",
      },
    },
    {
      entityId: ids.ENT_PC_MIRA,
      entityType: "player_character",
      title: "Mira Nightrill",
      summary: "Pícara mediana, rápida de manos y aún más rápida para oler problemas.",
      status: "active",
      importance: "normal",
      visibility: { kind: "party" },
      metadata: {
        isPremade: true,
        className: "Pícara",
        level: 1,
        species: "Mediana",
        background: "Criminal reformada",
        armorClass: 14,
        hitPointsCurrent: 8,
        hitPointsMax: 8,
        hitDice: "1d8",
        speed: 25,
        initiative: 3,
        passivePerception: 14,
        passiveInsight: 12,
        passiveInvestigation: 13,
        strength: 8,
        dexterity: 17,
        constitution: 12,
        intelligence: 13,
        wisdom: 14,
        charisma: 11,
        skills: ["stealth", "sleight_of_hand", "perception", "deception"],
        note: "Personaje pre-hecho disponible para elegir desde el portal de jugador.",
      },
    },
    {
      entityId: ids.ENT_PC_BROM,
      entityType: "player_character",
      title: "Brom Cindermug",
      summary: "Clérigo enano de manos ásperas y fe práctica. Busca un lugar donde su ayuda importe.",
      status: "active",
      importance: "normal",
      visibility: { kind: "party" },
      metadata: {
        isPremade: true,
        className: "Clérigo",
        level: 1,
        species: "Enano",
        background: "Artesano gremial",
        armorClass: 16,
        hitPointsCurrent: 10,
        hitPointsMax: 10,
        hitDice: "1d8",
        speed: 25,
        initiative: 0,
        passivePerception: 15,
        passiveInsight: 15,
        passiveInvestigation: 10,
        strength: 14,
        dexterity: 10,
        constitution: 15,
        intelligence: 10,
        wisdom: 16,
        charisma: 12,
        skills: ["medicine", "insight", "religion", "history"],
        note: "Personaje pre-hecho disponible para elegir desde el portal de jugador.",
      },
    },
    {
      entityId: ids.ENT_PC_NIM,
      entityType: "player_character",
      title: "Nimue Ashbottle",
      summary: "Maga elfa, curiosa y metódica. Sospecha que Phandalin oculta magia anterior al pueblo actual.",
      status: "active",
      importance: "normal",
      visibility: { kind: "party" },
      metadata: {
        isPremade: true,
        className: "Maga",
        level: 1,
        species: "Elfa",
        background: "Sabia",
        armorClass: 12,
        hitPointsCurrent: 6,
        hitPointsMax: 6,
        hitDice: "1d6",
        speed: 30,
        initiative: 2,
        passivePerception: 13,
        passiveInsight: 13,
        passiveInvestigation: 15,
        strength: 8,
        dexterity: 14,
        constitution: 12,
        intelligence: 16,
        wisdom: 13,
        charisma: 10,
        skills: ["arcana", "history", "investigation", "insight"],
        note: "Personaje pre-hecho disponible para elegir desde el portal de jugador.",
      },
    },
  ];

  for (const pc of PREMADE) {
    await api("POST", `/api/campaigns/${CMP}/entities`, { ...pc, actorId: "usr_dm" });
  }
  console.log(`✓ ${PREMADE.length} pre-made characters created`);
}
