import { api } from "./client.js";
import { CMP } from "./config.js";
import * as ids from "./ids.js";

function clue(entityId: string, title: string, subtitle: string, summary: string, status: string, importance: string, visibility: { kind: "party" | "dm_only" }, content: string, useAtTable: string, extra: Record<string, unknown> = {}) {
  return { entityId, title, subtitle, summary, status, importance, visibility, metadata: { content, useAtTable, ...extra } };
}

export async function seedClues() {
  const party = { kind: "party" as const };
  const dm = { kind: "dm_only" as const };
  const CLUES = [
    clue(ids.ENT_CLUE_DEAD_HORSES, "Caballos muertos en el camino", "La emboscada no fue aleatoria", "Dos caballos con flechas negras bloquean la ruta. Pertenecían a Gundren y Sildar.", "revealed", "high", party, "Los caballos fueron abatidos antes de que la caravana llegase. Las alforjas están saqueadas y hay marcas de arrastre hacia el norte.", "Da una pista física clara sin revelar todavía dónde está Gundren.", { discoveredAt: "Sesión 1" }),
    clue(ids.ENT_CLUE_GOBLIN_TRAIL, "Rastro goblin hacia el arroyo", "Entrada a la guarida Cragmaw", "Huellas pequeñas, ramas rotas y una cuerda-trampa señalan un sendero oculto.", "revealed", "high", party, "El rastro permite encontrar la guarida si el grupo investiga la emboscada en lugar de seguir directamente a Phandalin.", "Premia observación, supervivencia o buenas preguntas.", { discoveredAt: "Sesión 1" }),
    clue(ids.ENT_CLUE_SILDAR_WARNING, "Advertencia de Sildar", "Gundren sabe demasiado", "Sildar confirma que Gundren encontró algo importante antes de desaparecer.", "revealed", "critical", party, "Gundren descubrió una ruta hacia una antigua mina, pero alguien se enteró antes de que pudiera proteger el mapa.", "Conecta el rescate inicial con la amenaza mayor.", { discoveredAt: "Sesión 1" }),
    clue(ids.ENT_CLUE_REDBRAND_THREATS, "Amenazas de capas rojas", "Phandalin está intimidado", "Varias familias han pagado o callado por miedo a represalias Redbrand.", "revealed", "high", party, "Los Redbrands eligen víctimas, castigan públicamente y parecen saber cuándo actuar sin que nadie los frene.", "Activa el arco urbano y da permiso moral para intervenir.", { discoveredAt: "Sesión 2" }),
    clue(ids.ENT_CLUE_TOWN_FEARS, "El miedo del pueblo", "Nadie espera ayuda oficial", "Los vecinos bajan la voz al hablar de los Redbrands y evitan mirar al alcalde.", "revealed", "normal", party, "Phandalin no necesita héroes perfectos; necesita a alguien que rompa la inercia del miedo.", "Textura social para hacer cómodo el rol en el pueblo.", { discoveredAt: "Sesión 2" }),
    clue(ids.ENT_CLUE_CARP_TUNNEL, "Carp vio una entrada secreta", "Un niño encontró lo que los adultos ignoran", "Carp puede describir un túnel oculto cerca de Tresendar si el grupo lo escucha.", "prepared", "high", party, "Hay una entrada secundaria al complejo Redbrand que evita la puerta obvia y premia la relación con Qelline y Carp.", "Entrega una alternativa amable a grupos nuevos o niños que disfrutan investigando sin presión."),
    clue(ids.ENT_CLUE_SLEEPING_GIANT_BOAST, "Bravuconada del Gigante Dormido", "Los matones hablan de más", "Un Redbrand presume de que el jefe tiene ojos incluso donde no hay ventanas.", "prepared", "normal", dm, "La frase apunta al nothic y al control paranoico dentro de Tresendar.", "Úsala antes del dungeon para sembrar rareza y no solo amenaza callejera."),
    clue(ids.ENT_CLUE_RED_BRAND_LEDGER, "Libro de deudas Redbrand", "Miedo convertido en contabilidad", "Un registro de pagos, castigos y favores revela que la banda gobierna por economía tanto como por violencia.", "prepared", "high", dm, "El libro conecta víctimas, Halia, Harbin y comerciantes locales con distintos niveles de miedo o conveniencia.", "Sirve para convertir un combate ganado en consecuencias políticas."),
    clue(ids.ENT_CLUE_GLASSTAFF_LETTER, "Carta firmada con cristal azul", "Glasstaff responde ante alguien", "Un mensaje incompleto ordena vigilar a aventureros que hagan preguntas sobre Gundren.", "prepared", "critical", dm, "La carta conecta a Glasstaff con la Araña Negra sin revelar aún toda la red.", "Déjala en la Mansión Tresendar cuando el grupo registre el laboratorio."),
    clue(ids.ENT_CLUE_NOTHIC_WHISPERS, "Susurros bajo Tresendar", "Algo sabe secretos que no debería", "Una presencia invisible menciona culpas, miedos o deseos privados de los personajes.", "prepared", "high", dm, "El nothic puede oler secretos y revelar que Glasstaff no controla todo lo que vive bajo la mansión.", "Haz una oferta incómoda: información a cambio de comida, memoria o silencio."),
    clue(ids.ENT_CLUE_MIRNA_HEIRLOOM, "Recuerdo de Mirna", "Una deuda de gratitud", "Mirna conoce un viejo escondite familiar en Thundertree y puede ofrecer esa información si la salvan.", "prepared", "normal", party, "El rescate de la familia Dendrar abre un hilo opcional hacia Thundertree sin parecer encargo aleatorio.", "Recompensa emocional, no solo tesoro."),
    clue(ids.ENT_CLUE_HALIA_OFFER, "Oferta de Halia", "Ayuda con precio político", "Halia puede señalar debilidades de los Redbrands, pero quiere influencia a cambio.", "prepared", "normal", dm, "Halia no quiere salvar Phandalin por altruismo. Quiere que el vacío de poder la favorezca.", "Preséntala si el grupo busca soluciones no violentas o alianzas locales."),
    clue(ids.ENT_CLUE_HARBIN_NOTICE, "Anuncios del Salón del Concejo", "Problemas que la autoridad externaliza", "El tablón ofrece recompensas por amenazas externas mientras evita hablar de Redbrands.", "prepared", "normal", party, "Harbin intenta dirigir a los aventureros lejos del problema político central.", "Úsala para abrir side quests sin perder la crítica al alcalde."),
    clue(ids.ENT_CLUE_DARAN_REPORT, "Informe viejo de Daran", "Patrones de ocupación", "Daran reconoce que los Redbrands actúan como tropa bajo mando, no como borrachos sueltos.", "prepared", "normal", party, "La disciplina de los matones sugiere que alguien con entrenamiento o magia los está organizando.", "Sirve para grupos que preguntan por estrategia."),
    clue(ids.ENT_CLUE_LINENE_CARGO_MARKS, "Marcas del cargamento Lionshield", "Robo rastreable", "Sellos en cajas recuperadas conectan goblins, rutas comerciales y compradores que se benefician del caos.", "prepared", "normal", party, "Parte del cargamento aparece en manos goblin y parte podría haber acabado en tratos locales.", "Convierte una recompensa pequeña en pista económica."),
    clue(ids.ENT_CLUE_CASTLE_MARKS, "Marcas hacia el castillo", "Ruta incompleta Cragmaw", "Símbolos goblin y referencias a un viejo castillo permiten acotar la búsqueda.", "prepared", "high", dm, "Con dos fuentes distintas, el grupo puede triangular el camino hacia el Castillo Cragmaw.", "Entrégala tras negociar con goblins o interrogar a un superviviente."),
    clue(ids.ENT_CLUE_CRAGMAW_RANSOM, "Mensaje de rescate Cragmaw", "Gundren tiene precio", "Un mensaje sucio deja claro que Gundren vale más vivo que muerto, al menos por ahora.", "prepared", "critical", dm, "Grol y la Araña Negra no tienen exactamente los mismos incentivos, lo que abre oportunidad al grupo.", "Úsalo para poner reloj sin matar a Gundren fuera de pantalla."),
    clue(ids.ENT_CLUE_VYERITH_DISGUISE, "Detalles que no encajan", "Una identidad falla bajo presión", "Una supuesta aliada o prisionera sabe demasiado poco de lo que dice ser.", "prepared", "high", dm, "Vyerith puede estar disfrazada y usar la confusión del castillo para mover el mapa.", "Entrega microcontradicciones, no un cartel de 'doppleganger'."),
    clue(ids.ENT_CLUE_GROL_BARGAIN, "La negociación de Grol", "El mapa es mercancía", "Grol no es devoto de la Araña Negra; está calculando precio, miedo y oportunidad.", "prepared", "high", dm, "El jefe Cragmaw puede traicionar un trato si cree que mejora su posición.", "Permite resolver el castillo con conversación tensa o doble cruce."),
    clue(ids.ENT_CLUE_NUNDRO_TESTIMONY, "Testimonio de Nundro", "La mina ya fue ocupada", "Nundro vio símbolos de araña negra antes de ser separado de sus hermanos.", "prepared", "critical", dm, "Nundro puede confirmar que la Araña Negra llegó a la Cueva del Eco de la Ola antes que el grupo.", "Recompensa emocional al rescate, no simple exposición."),
    clue(ids.ENT_CLUE_SPIDER_SIGIL, "Sello de araña negra", "Firma del antagonista", "Un sello discreto aparece en mensajes, pagos y órdenes aparentemente inconexas.", "prepared", "high", dm, "El símbolo permite que los jugadores reconozcan la mano de un enemigo común antes de conocer su nombre real.", "Repite el símbolo tres veces en escenas distintas para crear memoria visual."),
    clue(ids.ENT_CLUE_MINE_MAP, "Mapa de Gundren", "La ruta hacia la mina perdida", "El mapa es el objeto que todos quieren controlar.", "prepared", "critical", dm, "El mapa no solo indica una entrada; también muestra marcas antiguas que sugieren peligros internos.", "Hazlo tangible: una copia parcial para jugadores funciona muy bien."),
    clue(ids.ENT_CLUE_FORGE_ECHO, "Eco mágico en la roca", "La forja no es leyenda", "La piedra de la mina conserva resonancias arcanas que responden a conjuros o símbolos enanos.", "prepared", "high", dm, "La Cueva del Eco de la Ola contiene un fenómeno real, no solo riqueza mineral.", "Introduce maravilla antes del combate final."),
    clue(ids.ENT_CLUE_THARDEN_BODY, "El destino de Tharden", "La mina ya cobró precio", "El cuerpo o las pertenencias de Tharden muestran que la Araña Negra llegó antes y no dejó testigos útiles.", "prepared", "critical", dm, "La familia Rockseeker ya ha perdido a uno de los suyos por esta carrera.", "Haz silencio un momento. Esta pista cambia el tono."),
    clue(ids.ENT_CLUE_REIDOTH_WARNING, "Advertencia de Reidoth", "No todo tesoro merece el camino", "Reidoth conoce rutas y peligros, pero advierte que Thundertree no es un paseo heroico.", "prepared", "normal", dm, "El druida puede orientar hacia Cragmaw o Thundertree, pero exige respeto por el riesgo.", "Usa a Reidoth para enseñar que decidir no entrar también es jugar bien."),
    clue(ids.ENT_CLUE_DRAGON_SIGNS, "Señales de dragón", "El depredador no se esconde del todo", "Árboles marcados, silencio animal y olores acres indican que algo grande reclama Thundertree.", "prepared", "high", dm, "Venomfang deja suficientes señales para que una mesa cuidadosa entienda el peligro antes de verlo.", "Nunca hagas que el dragón parezca encuentro obligatorio."),
    clue(ids.ENT_CLUE_OLD_OWL_SIGNS, "Signos del Viejo Pozo", "Magia que no pertenece al pueblo", "Restos de ritual, no muertos y notas arcanas sugieren una investigación peligrosa pero separada de los Redbrands.", "prepared", "normal", party, "Hamun Kost no está necesariamente conectado a la Araña Negra, lo que enseña a no simplificar todos los misterios.", "Buen descanso de la trama central sin perder tono."),
    clue(ids.ENT_CLUE_AGATHA_MEMORY, "Memoria de Agatha", "Una respuesta con coste", "Agatha puede recordar nombres, mapas o libros, pero la pregunta debe ser precisa.", "prepared", "normal", dm, "La banshee sabe mucho, pero no existe para resolver toda la campaña.", "Obliga al grupo a decidir qué necesita saber de verdad."),
    clue(ids.ENT_CLUE_WYVERN_TOR_RAIDS, "Rastros de asalto del Tor", "La frontera se mueve", "Huellas pesadas y restos de campamentos muestran que los orcos prueban rutas de Phandalin.", "prepared", "normal", party, "La amenaza exterior sube si el grupo se centra solo en política urbana.", "Úsala como frente si necesitas presión entre sesiones."),
    clue(ids.ENT_CLUE_PHANDALIN_POWER_VACUUM, "Vacío de poder en Phandalin", "La victoria también crea problemas", "Cuando caen los Redbrands, varias personas intentan decidir qué significa 'orden' para el pueblo.", "prepared", "high", dm, "Eliminar una banda no crea automáticamente justicia; crea espacio para el siguiente poder.", "Sirve para el epílogo y para que las decisiones sociales importen."),
  ];

  for (const clueSeed of CLUES) {
    await api("POST", `/api/campaigns/${CMP}/entities`, { actorId: "usr_dm", entityType: "clue", ...clueSeed });
  }
  console.log(`✓ ${CLUES.length} clues created`);
}
