import { api } from "./client.js";
import { CMP } from "./config.js";
import * as ids from "./ids.js";

export async function seedLocations() {
  const party = { kind: "party" as const };
  const dm = { kind: "dm_only" as const };
  const LOCATIONS = [
    { entityId: ids.ENT_LOC_PHANDALIN, title: "Phandalin", subtitle: "Pueblo de frontera", summary: "Asentamiento minero en reconstrucción: calles embarradas, casas nuevas sobre piedra antigua y una comunidad que quiere paz pero ya no confía en sus autoridades.", status: "active", importance: "critical", visibility: party, metadata: { tableUse: "Centro social de la campaña. Cada visita debe cambiar una relación, revelar un rumor o mostrar una consecuencia." } },
    { entityId: ids.ENT_LOC_TRIBOAR_TRAIL, title: "Camino de Triboar", subtitle: "Ruta de caravana", summary: "Camino de entrada a la campaña, útil para emboscadas, rastros goblin y sensación de región peligrosa.", status: "visited", importance: "high", visibility: party, metadata: { tableUse: "Recordatorio físico de que la aventura empezó por una desaparición, no por una taberna." } },
    { entityId: ids.ENT_LOC_CRAGMAW_HIDEOUT, title: "Guarida Cragmaw", subtitle: "Cueva junto al arroyo", summary: "Escondite goblin con trampas, corriente fuerte, prisioneros y una disputa interna que permite negociar o dividir enemigos.", status: "visited", importance: "high", visibility: party, metadata: { scenes: ["Entrada con lobos", "Trampa de riada", "Cámara de Klarg", "Negociación de Yeemik"] } },
    { entityId: ids.ENT_LOC_STONEHILL, title: "Posada Stonehill", subtitle: "Refugio social", summary: "La sala común donde se oye lo que el pueblo no se atreve a decir en voz alta.", status: "known", importance: "high", visibility: party, metadata: { tableUse: "Lugar ideal para abrir sesiones con rumores, descanso y presión social." } },
    { entityId: ids.ENT_LOC_BARTHEN, title: "Provisiones de Barthen", subtitle: "Comercio local", summary: "Destino de la caravana de Gundren y punto natural para confirmar que algo salió mal.", status: "known", importance: "normal", visibility: party, metadata: { tableUse: "Exposición amable y recompensas básicas sin convertirlo en infodump." } },
    { entityId: ids.ENT_LOC_LIONSHIELD, title: "Lionshield Coster", subtitle: "Almacén de mercancías", summary: "Comercio con cargamento robado por goblins. Útil para dar una recompensa clara y conectar goblins con economía local.", status: "known", importance: "normal", visibility: party, metadata: { tableUse: "Buen punto para que una jugadora práctica vea impacto inmediato." } },
    { entityId: ids.ENT_LOC_TRESENDAR, title: "Mansión Tresendar", subtitle: "Ruinas con sótanos", summary: "Guarida urbana de los Redbrands bajo una casa noble abandonada. Es el primer gran dungeon social de la campaña.", status: "available", importance: "critical", visibility: party, metadata: { tableUse: "Debe sentirse como liberar el pueblo, no solo limpiar habitaciones." } },
    { entityId: ids.ENT_LOC_SLEEPING_GIANT, title: "El Gigante Dormido", subtitle: "Taberna tomada por Redbrands", summary: "Local áspero usado por los matones para presumir, beber y probar los límites de la autoridad del grupo.", status: "available", importance: "high", visibility: party, metadata: { tableUse: "Encuentro de tensión antes de Tresendar; permite combate, intimidación o engaño." } },
    { entityId: ids.ENT_LOC_TOWNMASTER, title: "Salón del Concejo", subtitle: "Oficina de Harbin Wester", summary: "Edificio oficial con tablón de anuncios, contratos menores y silencios incómodos del alcalde.", status: "known", importance: "normal", visibility: party, metadata: { tableUse: "Contrasta la autoridad formal con la autoridad real de los Redbrands." } },
    { entityId: ids.ENT_LOC_SHRINE, title: "Santuario de la Suerte", subtitle: "Pequeño templo", summary: "Santuario discreto atendido por Garaele, con contactos externos y rumores más fiables que los de taberna.", status: "known", importance: "normal", visibility: party, metadata: { tableUse: "Sirve para introducir Agatha, preguntas espirituales y facciones buenas sin sermón." } },
    { entityId: ids.ENT_LOC_EDERMATH, title: "Huerto Edermath", subtitle: "Retiro de veterano", summary: "Refugio tranquilo de Daran, que observa a los Redbrands con preocupación de soldado viejo.", status: "known", importance: "normal", visibility: party, metadata: { tableUse: "Aliado para grupos que buscan consejo táctico." } },
    { entityId: ids.ENT_LOC_ALDERLEAF, title: "Granja Alderleaf", subtitle: "Casa de Qelline y Carp", summary: "Hogar cálido que recuerda que Phandalin tiene familias, no solo ganchos de misión.", status: "known", importance: "normal", visibility: party, metadata: { tableUse: "Buen lugar para hacer cómoda la investigación con niños o jugadores nuevos." } },
    { entityId: ids.ENT_LOC_MINERS_EXCHANGE, title: "Intercambio de Mineros", subtitle: "Centro económico", summary: "Lugar donde se pesan hallazgos, circulan rumores de vetas y Halia mide quién puede gobernar el futuro económico del pueblo.", status: "known", importance: "high", visibility: party, metadata: { tableUse: "Permite conversaciones políticas sin apartarse de la aventura." } },
    { entityId: ids.ENT_LOC_CRAGMAW_CASTLE, title: "Castillo Cragmaw", subtitle: "Fortaleza oculta", summary: "Ruina tomada por goblins donde Gundren, el mapa o ambos pueden cambiar de manos.", status: "hidden", importance: "critical", visibility: dm, metadata: { tableUse: "Dungeon de rescate y negociación. No lo dirijas solo como asalto frontal." } },
    { entityId: ids.ENT_LOC_WAVE_ECHO, title: "Cueva del Eco de la Ola", subtitle: "Mina perdida", summary: "Complejo minero antiguo ligado a magia resonante, tragedia familiar y la ambición de la Araña Negra.", status: "hidden", importance: "critical", visibility: dm, metadata: { tableUse: "Final de exploración: alterna maravilla, peligro ambiental y presión antagonista." } },
    { entityId: ids.ENT_LOC_FORGE_OF_SPELLS, title: "Forja de Conjuros", subtitle: "Corazón arcano de la mina", summary: "Foco mágico dañado que todavía puede cargar armas, despertar guardianes y atraer a quien quiera controlar la región.", status: "hidden", importance: "critical", visibility: dm, metadata: { tableUse: "Haz que el tesoro central sea una decisión moral, no solo botín." } },
    { entityId: ids.ENT_LOC_CONYBERRY, title: "Ruinas de Conyberry", subtitle: "Camino hacia Agatha", summary: "Restos de una aldea destruida que preparan un cambio de tono antes de entrar en el territorio de una presencia antigua.", status: "available", importance: "normal", visibility: party, metadata: { tableUse: "Escena corta de viaje, memoria y silencio." } },
    { entityId: ids.ENT_LOC_AGATHA_LAIR, title: "Morada de Agatha", subtitle: "Refugio espectral", summary: "Lugar de negociación sobrenatural donde la cortesía importa tanto como la magia.", status: "hidden", importance: "high", visibility: dm, metadata: { tableUse: "Encuentro social con tensión; evita convertirlo en combate gratuito." } },
    { entityId: ids.ENT_LOC_OLD_OWL_WELL, title: "Viejo Pozo del Búho", subtitle: "Ruina arcana", summary: "Restos antiguos con actividad no muerta y un mago que no encaja del todo como villano principal.", status: "available", importance: "normal", visibility: party, metadata: { tableUse: "Side quest para mostrar que no todo problema se resuelve matando." } },
    { entityId: ids.ENT_LOC_WYVERN_TOR, title: "Tor del Guiverno", subtitle: "Campamento orco", summary: "Refugio de asaltantes que presionan rutas y pueden volverse urgentes si el grupo ignora el exterior.", status: "available", importance: "normal", visibility: party, metadata: { tableUse: "Frente de combate claro para sesiones de acción directa." } },
    { entityId: ids.ENT_LOC_THUNDERTREE, title: "Thundertree", subtitle: "Ruinas invadidas por ceniza y verdor", summary: "Pueblo arruinado donde un druida, muertos de ceniza y un dragón joven compiten por el control del espacio.", status: "hidden", importance: "high", visibility: dm, metadata: { tableUse: "Side quest de alto riesgo: deja muy claro que huir también es una decisión inteligente." } },
  ];

  for (const loc of LOCATIONS) {
    await api("POST", `/api/campaigns/${CMP}/entities`, { actorId: "usr_dm", entityType: "location", ...loc });
  }
  console.log(`✓ ${LOCATIONS.length} locations created`);
}
