import { api } from "./client.js";
import { CMP } from "./config.js";
import * as ids from "./ids.js";

export async function seedNpcs() {
  const party = { kind: "party" as const };
  const dm = { kind: "dm_only" as const };
  const NPCS = [
    { entityId: ids.ENT_NPC_GUNDREN, title: "Gundren Rockseeker", subtitle: "Patrón desaparecido", summary: "Enano entusiasta que contrató a la caravana y guarda información crucial sobre la mina perdida.", status: "missing", importance: "critical", visibility: party, metadata: { desire: "Recuperar a sus hermanos y abrir la mina sin que caiga en manos depredadoras.", atTable: "Habla rápido, confía demasiado, ama sus planes antes de que funcionen." } },
    { entityId: ids.ENT_NPC_SILDAR, title: "Sildar Hallwinter", subtitle: "Veterano honorable", summary: "Aliado de Gundren y posible mentor para el grupo. Quiere restaurar el orden en Phandalin.", status: "known", importance: "critical", visibility: party, metadata: { desire: "Encontrar a Iarno, salvar a Gundren y que Phandalin tenga una autoridad decente.", atTable: "Directo, cansado, agradecido; no le robes agencia a los jugadores." } },
    { entityId: ids.ENT_NPC_ELMAR, title: "Elmar Barthen", subtitle: "Comerciante", summary: "Primer contacto amable en el pueblo; sabe quién esperaba a Gundren y quién hace preguntas incómodas.", status: "known", importance: "normal", visibility: party, metadata: { desire: "Que la caravana llegue y el pueblo no se rompa por miedo." } },
    { entityId: ids.ENT_NPC_TOBLEN, title: "Toblen Stonehill", subtitle: "Posadero atento", summary: "Conoce el pulso social de Phandalin y ayuda a que el grupo escuche rumores sin sentirse interrogado.", status: "known", importance: "normal", visibility: party, metadata: { desire: "Mantener la posada como refugio neutral." } },
    { entityId: ids.ENT_NPC_TRILENA, title: "Trilena Stonehill", subtitle: "Voz preocupada del pueblo", summary: "Puede poner rostro humano a los abusos Redbrand y contar lo que otros callan.", status: "known", importance: "normal", visibility: party, metadata: { desire: "Que alguien actúe sin que su familia pague el precio." } },
    { entityId: ids.ENT_NPC_HARBIN, title: "Harbin Wester", subtitle: "Alcalde nervioso", summary: "Autoridad oficial de Phandalin, más preocupado por no enfadar a los Redbrands que por liderar.", status: "known", importance: "high", visibility: party, metadata: { desire: "Sobrevivir políticamente y físicamente; en ese orden variable.", atTable: "No lo conviertas en chiste puro: su cobardía debe incomodar." } },
    { entityId: ids.ENT_NPC_HALIA, title: "Halia Thornton", subtitle: "Maestra de gremio", summary: "Comerciante pragmática que ofrece ayuda si puede ganar influencia a cambio.", status: "known", importance: "critical", visibility: party, metadata: { desire: "Que Phandalin sea estable, rentable y dependiente de ella.", atTable: "Nunca miente si una media verdad le basta." } },
    { entityId: ids.ENT_NPC_GARAELE, title: "Hermana Garaele", subtitle: "Acólita del santuario", summary: "Busca información espiritual y puede orientar al grupo hacia amenazas mayores.", status: "available", importance: "normal", visibility: party, metadata: { desire: "Obtener respuestas sin poner a inocentes en manos de fuerzas antiguas." } },
    { entityId: ids.ENT_NPC_DARAN, title: "Daran Edermath", subtitle: "Veterano retirado", summary: "Observador sereno que reconoce patrones de abuso y puede recomendar actuar contra los Redbrands.", status: "available", importance: "normal", visibility: party, metadata: { desire: "Que la próxima generación no aprenda a vivir arrodillada." } },
    { entityId: ids.ENT_NPC_QELLINE, title: "Qelline Alderleaf", subtitle: "Granjera hospitalaria", summary: "Vecina atenta, útil para mostrar el lado cotidiano de Phandalin y sus rutas seguras.", status: "available", importance: "normal", visibility: party, metadata: { desire: "Proteger a Carp y ayudar sin llamar la atención de violentos." } },
    { entityId: ids.ENT_NPC_CARP, title: "Carp Alderleaf", subtitle: "Niño demasiado curioso", summary: "Ha visto más de lo que entiende y puede revelar una entrada secreta si el grupo lo escucha con cariño.", status: "available", importance: "high", visibility: party, metadata: { desire: "Ser tratado como útil, no como estorbo.", atTable: "Ideal para partidas familiares: una pista clara en una voz cercana." } },
    { entityId: ids.ENT_NPC_LINENE, title: "Linene Graywind", subtitle: "Mercader de Lionshield", summary: "Quiere recuperar cargamento robado y tiene poca paciencia con aventureros irresponsables.", status: "known", importance: "normal", visibility: party, metadata: { desire: "Que el comercio vuelva a ser predecible." } },
    { entityId: ids.ENT_NPC_MIRNA, title: "Mirna Dendrar", subtitle: "Vecina retenida", summary: "Su familia representa el coste humano del dominio Redbrand y puede ofrecer una recompensa emocional, no solo económica.", status: "missing", importance: "high", visibility: party, metadata: { desire: "Sacar a sus hijos del sótano y reconstruir una vida." } },
    { entityId: ids.ENT_NPC_IARNO, title: "Iarno Albrek", subtitle: "Mago desaparecido", summary: "Antiguo enviado de la Alianza. Su ausencia es demasiado conveniente.", status: "hidden", importance: "critical", visibility: dm, metadata: { desire: "Gobernar desde la sombra sin responder ante la Alianza.", atTable: "No lo presentes como villano de cartel; fue una solución institucional que se pudrió." } },
    { entityId: ids.ENT_NPC_GLASSTAFF_ALIAS, title: "Glasstaff", subtitle: "Alias de terror urbano", summary: "Nombre que los Redbrands respetan y el pueblo teme. Sirve como máscara narrativa antes de revelar a Iarno.", status: "hidden", importance: "critical", visibility: dm, metadata: { desire: "Separar al mago respetable del jefe criminal." } },
    { entityId: ids.ENT_NPC_NOTHIC, title: "El nothic de Tresendar", subtitle: "Hambre y secretos", summary: "Criatura rota por magia y hambre mental. Puede ser monstruo, informante o espejo grotesco de los secretos del lugar.", status: "hidden", importance: "high", visibility: dm, metadata: { desire: "Comer, sobrevivir y saborear secretos ajenos.", atTable: "Haz que ofrezca información incómoda a cambio de algo moralmente feo." } },
    { entityId: ids.ENT_NPC_GRISTA, title: "Grista", subtitle: "Tabernera del Gigante Dormido", summary: "Mantiene el local donde los Redbrands presumen. Sabe mucho, pero la prudencia le sale más rentable que la valentía.", status: "available", importance: "normal", visibility: party, metadata: { desire: "Que nadie destroce su negocio ni la arrastre a una guerra." } },
    { entityId: ids.ENT_NPC_KLARG, title: "Klarg", subtitle: "Jefe de la guarida", summary: "Bruto goblinoide que manda por fuerza, miedo y la promesa de recompensas superiores.", status: "active", importance: "high", visibility: dm, metadata: { desire: "Ser visto como jefe temible aunque otros muevan piezas más grandes." } },
    { entityId: ids.ENT_NPC_YEEMIK, title: "Yeemik", subtitle: "Segundo ambicioso", summary: "Goblin dispuesto a negociar si eso le acerca al poder dentro de la guarida.", status: "available", importance: "high", visibility: dm, metadata: { desire: "Reemplazar a Klarg y salir vivo." } },
    { entityId: ids.ENT_NPC_GROL, title: "Rey Grol", subtitle: "Jefe Cragmaw", summary: "Goblinoide que puede vender prisioneros, mapas o lealtades al mejor postor.", status: "hidden", importance: "critical", visibility: dm, metadata: { desire: "Sacar precio máximo por Gundren y el mapa." } },
    { entityId: ids.ENT_NPC_VYERITH, title: "Vyerith", subtitle: "Espía cambiante", summary: "Agente infiltrada que complica el rescate de Gundren y puede convertir certezas en sospechas.", status: "hidden", importance: "high", visibility: dm, metadata: { desire: "Asegurar que el mapa llegue a la Araña Negra aunque Grol negocie." } },
    { entityId: ids.ENT_NPC_NEZZNAR, title: "Nezznar, la Araña Negra", subtitle: "Antagonista oculto", summary: "Figura que tira de goblins, bandidos y espías para llegar a la mina antes que nadie.", status: "hidden", importance: "critical", visibility: dm, metadata: { desire: "Controlar la Forja de Conjuros y borrar competidores antes de que entiendan el tablero." } },
    { entityId: ids.ENT_NPC_NUNDRO, title: "Nundro Rockseeker", subtitle: "Superviviente", summary: "Hermano de Gundren. Puede confirmar qué ocurrió en la mina si el grupo lo encuentra a tiempo.", status: "hidden", importance: "critical", visibility: dm, metadata: { desire: "Sobrevivir, hallar a Gundren y llorar a Tharden cuando haya tiempo." } },
    { entityId: ids.ENT_NPC_THARDEN, title: "Tharden Rockseeker", subtitle: "Hermano caído", summary: "Su destino revela que la mina ya no es una promesa: es una tragedia en curso.", status: "hidden", importance: "high", visibility: dm, metadata: { desire: "Funciona como consecuencia emocional, no como PNJ activo." } },
    { entityId: ids.ENT_NPC_HAMUN, title: "Hamun Kost", subtitle: "Mago de ruinas", summary: "Investigador arcano en el Viejo Pozo del Búho. Sospechoso, peligroso, pero no necesariamente ligado a la Araña Negra.", status: "hidden", importance: "normal", visibility: dm, metadata: { desire: "Estudiar la ruina sin que aventureros simplifiquen su presencia." } },
    { entityId: ids.ENT_NPC_REIDOTH, title: "Reidoth", subtitle: "Druida de Thundertree", summary: "Guía cauteloso que sabe más de rutas y peligros naturales que casi cualquier vecino de Phandalin.", status: "hidden", importance: "high", visibility: dm, metadata: { desire: "Que la gente entienda que algunos lugares no se conquistan, se respetan." } },
    { entityId: ids.ENT_NPC_AGATHA, title: "Agatha", subtitle: "Banshee memoriosa", summary: "Presencia antigua que puede responder preguntas si el grupo trata el encuentro como una audiencia, no como saqueo.", status: "hidden", importance: "high", visibility: dm, metadata: { desire: "Ser recordada, respetada y no reducida a una máquina de respuestas." } },
    { entityId: ids.ENT_NPC_BRUGHOR, title: "Brughor Axe-Biter", subtitle: "Jefe de asaltantes", summary: "Líder orco del Tor del Guiverno. Amenaza directa para caminos y granjas si el grupo ignora la frontera.", status: "available", importance: "normal", visibility: dm, metadata: { desire: "Medir si Phandalin sigue siendo presa fácil." } },
    { entityId: ids.ENT_NPC_VENOMFANG, title: "Venomfang", subtitle: "Dragón joven astuto", summary: "Depredador inteligente de Thundertree. Su peligro real no son solo garras y veneno, sino su capacidad de ofrecer acuerdos tentadores.", status: "hidden", importance: "critical", visibility: dm, metadata: { desire: "Convertir a intrusos en herramientas o comida, según convenga." } },
  ];

  for (const npc of NPCS) {
    await api("POST", `/api/campaigns/${CMP}/entities`, { actorId: "usr_dm", entityType: "npc", ...npc });
  }
  console.log(`✓ ${NPCS.length} NPCs created`);
}
