import { api } from "./client.js";
import { CMP } from "./config.js";
import * as ids from "./ids.js";

function secret(entityId: string, title: string, subtitle: string, summary: string, importance: string, truth: string, revealTrigger: string) {
  return { entityId, title, subtitle, summary, status: "hidden", importance, metadata: { truth, revealTrigger } };
}

export async function seedSecrets() {
  const SECRETS = [
    secret(ids.ENT_SEC_IARNO_GLASSTAFF, "Iarno es Glasstaff", "La autoridad perdida dirige a los matones", "El enviado desaparecido de la Alianza lidera a los Redbrands desde los sótanos de Tresendar.", "critical", "Iarno Albrek no fue capturado: se reinventó como Glasstaff y usa a los Redbrands para controlar Phandalin.", "Laboratorio de Tresendar, carta de la Araña Negra, nothic negociador o confrontación directa."),
    secret(ids.ENT_SEC_NEZZNAR, "La Araña Negra coordina la región", "Un antagonista conecta goblins y bandidos", "Nezznar utiliza intermediarios para que nadie vea la red completa hasta que sea tarde.", "critical", "La Araña Negra financia o presiona a Cragmaw y Glasstaff para llegar antes que nadie a la Cueva del Eco de la Ola.", "Tres pistas con sello de araña, testimonio de Nundro, carta de Glasstaff o escena en la mina."),
    secret(ids.ENT_SEC_CASTLE_LOCATION, "El Castillo Cragmaw está oculto por rutas falsas", "Los goblins no usan una sola entrada", "El castillo no se encuentra siguiendo un camino principal; hay que reconstruir la ruta.", "critical", "Solo goblins, exploradores locales o mapas parciales conocen la combinación de marcas que lleva al castillo.", "Negociación con Yeemik, ayuda de Reidoth, rastros de Cragmaw o documentos en Tresendar."),
    secret(ids.ENT_SEC_GUNDREN_MAP, "El mapa de Gundren es la llave real", "Sin mapa, la mina sigue siendo mito", "Rescatar a Gundren no basta si el mapa ya cambió de manos.", "critical", "Gundren escondió suficiente información para llegar a la mina, pero el mapa puede terminar en manos de Grol, Vyerith o la Araña Negra.", "Interrogatorio de goblins, búsqueda en el castillo o recuperación de pertenencias."),
    secret(ids.ENT_SEC_HALIA_AMBITION, "Halia quiere heredar el vacío de poder", "Aliada útil, no inocente", "Su ayuda contra los Redbrands puede crear otro poder difícil de controlar.", "high", "Halia usa cualquier victoria del grupo para ganar influencia comercial y política en Phandalin.", "Tratos privados, recompensas selectivas, presión sobre Harbin o lectura del libro de deudas."),
    secret(ids.ENT_SEC_HARBIN_COWARDICE, "Harbin sabe más de lo que admite", "El miedo también es una elección política", "El alcalde no ignora el problema: ha elegido sobrevivir mirando hacia otro lado.", "normal", "Harbin ha recibido amenazas directas y prefiere sacrificar vecinos antes que exponerse personalmente.", "Presión social, prueba de pagos, confrontación tras ataque Redbrand o uso del tablón de anuncios."),
    secret(ids.ENT_SEC_CRAGMAW_BARGAIN, "Los Cragmaw pueden dividirse", "No todos obedecen por lealtad", "Yeemik, Grol y otros goblins pueden cambiar de bando si ven una oportunidad de ascenso.", "high", "La jerarquía Cragmaw es frágil: una negociación inteligente puede evitar combates y abrir rutas.", "Captura de goblin, negociación con Yeemik, demostración de fuerza contra Klarg o trato con Grol."),
    secret(ids.ENT_SEC_FORGE_REAL, "La Forja de Conjuros funciona parcialmente", "El tesoro central no es solo oro", "La mina conserva un foco arcano deteriorado, pero todavía peligroso y valioso.", "critical", "La Cueva del Eco de la Ola contiene una forja mágica dañada que puede alterar el equilibrio de poder de la región.", "Mapa completo, testimonio de Nundro, eco mágico en la roca o exploración profunda de la mina."),
    secret(ids.ENT_SEC_DENDRARS_ALIVE, "La familia Dendrar sigue viva", "Víctimas con reloj", "Los Redbrands mantienen rehenes que pueden desaparecer si el grupo retrasa demasiado Tresendar.", "high", "Mirna y sus hijos son moneda de presión y una posible venta futura, no simples prisioneros estáticos.", "Rumores en Stonehill, libro de deudas, exploración de celdas o negociación con Redbrands."),
    secret(ids.ENT_SEC_NOTHIC_HUNGER, "El nothic conoce secretos de Tresendar", "Un monstruo útil si pagas el precio", "La criatura bajo la mansión sabe quién manda, quién miente y qué temen los intrusos.", "high", "El nothic puede revelar pistas potentes, pero cada trato debe sentirse incómodo o peligroso.", "Primer contacto psíquico, oferta de carne, secreto personal o promesa de liberar su zona."),
    secret(ids.ENT_SEC_REDBRAND_HOSTAGES, "Los Redbrands planean trasladar rehenes", "La demora tiene coste", "Si el grupo no actúa, los rehenes pueden moverse fuera de Phandalin o usarse como seguro.", "high", "Glasstaff no quiere cadáveres innecesarios dentro de Tresendar si el pueblo empieza a mirar demasiado.", "Escuchar bravuconadas, interceptar orden o fallar una entrada sigilosa."),
    secret(ids.ENT_SEC_VYERITH_DOPPELGANGER, "Vyerith no es quien aparenta", "El castillo tiene una segunda mentira", "Una agente cambiante puede robar el mapa incluso si el grupo gana el combate principal.", "high", "Vyerith trabaja para la Araña Negra y puede adoptar identidades útiles durante el caos del Castillo Cragmaw.", "Detalles contradictorios, prueba social, magia de detección o persecución tras recuperar el mapa."),
    secret(ids.ENT_SEC_THARDEN_DEAD, "Tharden ya murió en la mina", "La victoria llega tarde para alguien", "El rescate de Nundro no repara toda la tragedia Rockseeker.", "critical", "Tharden Rockseeker fue asesinado o murió durante la toma de la mina por agentes de la Araña Negra.", "Exploración de Wave Echo, testimonio de Nundro, hallazgo de cuerpo o pertenencias."),
    secret(ids.ENT_SEC_HAMUN_NOT_PRIMARY, "Hamun Kost no es el villano central", "Amenaza lateral, no raíz", "Su necromancia es peligrosa, pero no todo hilo extraño pertenece a la Araña Negra.", "normal", "Hamun investiga por cuenta propia; puede ser enemigo, fuente incómoda o distracción según cómo trate el grupo la escena.", "Investigación del Viejo Pozo, conversación contenida o comparación de símbolos arcanos."),
    secret(ids.ENT_SEC_VENOMFANG_MANIPULATES, "Venomfang prefiere manipular antes que luchar", "Un dragón también negocia", "El dragón de Thundertree puede ofrecer rutas, mentiras o favores para usar al grupo contra sus propios problemas.", "high", "Venomfang mide a los aventureros y preferirá que resuelvan obstáculos por él si parecen útiles.", "Primer parlamento, señales de dragón ignoradas o encuentro con Reidoth."),
    secret(ids.ENT_SEC_AGATHA_KNOWS, "Agatha sabe más de una respuesta", "La pregunta importa", "La banshee puede revelar una localización, nombre o memoria, pero no resolverá todo gratis.", "normal", "Agatha conserva recuerdos que cruzan la región, pero su vanidad y dolor limitan lo que ofrece.", "Ofrenda adecuada, pregunta precisa o trato respetuoso."),
    secret(ids.ENT_SEC_WYVERN_ORCS_PRESSURE, "Los orcos prueban la debilidad de Phandalin", "La frontera lee el miedo", "Si los Redbrands dominan el pueblo, otras amenazas entienden que nadie protege los caminos.", "normal", "Los asaltos del Tor del Guiverno crecen si la región percibe que Phandalin está paralizado.", "Rastros de asalto, tablón de Harbin o consecuencia entre sesiones."),
    secret(ids.ENT_SEC_PHANDALIN_POWER_VACUUM, "Liberar Phandalin abre una lucha política", "El final urbano no es neutral", "Cuando caen los Redbrands, Halia, Harbin, Sildar, Daran y los vecinos compiten por definir el nuevo orden.", "critical", "La campaña no termina al matar villanos: el grupo deja un modelo de poder que afecta el futuro del pueblo.", "Después de Tresendar, al repartir recompensas, al decidir quién custodia la mina o durante el epílogo."),
  ];

  for (const secretSeed of SECRETS) {
    await api("POST", `/api/campaigns/${CMP}/entities`, {
      actorId: "usr_dm",
      entityType: "secret",
      visibility: { kind: "dm_only" },
      ...secretSeed,
    });
  }
  console.log(`✓ ${SECRETS.length} secrets created`);
}
